### ISSUE TITLE
Docs for Google Maps - Map Marker (Polyne) 

### ISSUE THREAD

**Issue by castrogarciajs** [nuxt/scripts#103]
Hello Nuxt team,

I need to implement the Polyne API, but I have to use the `@nuxt/scripts` module, I want to ask if there is any reference of how to implement that in Nuxt, I need to mark with a line the distance of two places.

Thank you for reading.

**Comment by harlan-zw** [comment]
Can you provide a link? It's not clear what service you're talking about.

**Comment by castrogarciajs** [comment]
Of course, 

### API
https://developers.google.com/maps/documentation/javascript/reference/advanced-markers?hl=es-419

Is there any documentation on how I can use it in conjunction with Nuxt script?

**Comment by mrc-bsllt** [comment]
Is there any news?

**Comment by harlan-zw** [comment]
Yes will be completed as part of https://github.com/nuxt/scripts/pull/191
