### ISSUE TITLE
apiHost option for plausible

### ISSUE THREAD

**Issue by dev-cetus** [nuxt/scripts#104]
For plausible, you'd have to add an `apiHost` option, as [@nuxtjs/plausible](https://nuxt.com/modules/plausible#module-options) does, because plausible can also be installed in self-hosted mode.

**Comment by harlan-zw** [comment]
The API host is by default where the script is being loaded from when using the third-party script. This module uses a NPM module instead which can't infer the domain, hence why it exists.

You can change the src of the like the below, which will change the API host to `my-self-hosted-plausible.io`.

```ts
useScriptPlausible({
  scriptInput: {
    src: 'https://my-self-hosted-plausible.io/js/script.js'
  }
})
```

I've added a note for this in the docs but let me know if it's not clear.

**Comment by dev-cetus** [comment]
Okay just one question, it changes for `js/script.js`, but will it also change for event sending (it seems to me that it's a different script)?
