### ISSUE TITLE
Adding link preload

### ISSUE THREAD

**Issue by konstantin-karlovich-unbiased-co-uk** [nuxt/scripts#132]
Is there any way to add link preload in head when using external script using this module?

**Comment by harlan-zw** [comment]
Hi, could you provide some more context on what script you're loading and why you'd like to preload?

Doing so may be an anti-pattern depending on the script you need.

**Comment by harlan-zw** [comment]
You can provide the trigger as server and it will load the script eagerly as if you used `useHead`.

```ts
useScript('/script.js', { trigger: 'server' })
```

This will slow down your Nuxt hydration but it's a bit of a trade-off with A+B, you'd be better of implementing your A+B testing server side using `useState` so you can avoid the flash of content.

**Comment by harlan-zw** [comment]
> Such an entry in nuxt.config doesn't seem to work

Thanks for flagging this, I've pushed up a fix in 0.6.2.

> Also after the build I get this error

Are you using this composable? This was renamed in [0.6.0](https://github.com/nuxt/scripts/releases/tag/v0.6.0) as a breaking change. You should use `useScriptTriggerElement` now.

I believe Nuxt will sync the new composable names in the next version.

**Comment by harlan-zw** [comment]
No problem, happy to help where I can as the module is not publically announced so it has some rough edges still.
