### ISSUE TITLE
Unterminated regular expression error in 0.6.2

### ISSUE THREAD

**Issue by benfeather** [nuxt/scripts#136]
After upgrading @nuxt/scripts to 0.6.2 and updating my global scripts from an array to an object, I'm getting this error:

![CleanShot 2024-07-08 at 10 03 12@2x](https://github.com/nuxt/scripts/assets/43571410/e60d176c-ea4a-41a5-a05b-cd0e05a0100a)

Not sure Why the error lists the "YouTube embed" component, but the the error only occurs if @nuxt/scripts is enabled.

I have tried removing the "YouTube embed" component and I'm still getting the error, so I believe it's an issue with the scripts package.

**Comment by benfeather** [comment]
That component is using the "useScriptTag" composable, not sure if that would cause the error, but it did the same thing when disabled, so not sure.

**Comment by harlan-zw** [comment]
@huang-julien seems like a bug with the AST parsing of vue code which includes `useScript`. 

I think maybe we should catch the exception thrown from the transforms and allow any issues to propagate through the rest of the rollup plugins.

**Comment by harlan-zw** [comment]
Thanks for reporting, should be fixed in 0.6.4.
