### ISSUE TITLE
googleTagManager `$production` token configuration is broken

### ISSUE THREAD

**Issue by Kronhyx** [nuxt/scripts#143]
# Environment
- Operating System: `MacOS`
- Node Version: `v21.6.2`
- Nuxt Version: `3.12.3`
- Nitro Version: `2.9.7`

```ts
import { defineNuxtConfig } from 'nuxt/config';

export default defineNuxtConfig({
$production: {
    scripts: {
      registry: {
        googleTagManager: {
          token: 'GTM-MYCUSTOMID,
        },
      },
    },
  },
})
```

### current result:
> https://www.googletagmanager.com/gtm.js

### expected result:
> https://www.googletagmanager.com/gtm.js?id=GTM-MYCUSTOMID

<hr>

### Using `id` instead `token`

```ts
import { defineNuxtConfig } from 'nuxt/config';

export default defineNuxtConfig({
$production: {
    scripts: {
      registry: {
        googleTagManager: {
          id: 'GTM-MYCUSTOMID,
        },
      },
    },
  },
})
```

### final result:
> https://www.googletagmanager.com/gtm.js?id=GTM-MYCUSTOMID

**Comment by huang-julien** [comment]
Hello, gtm should be using id insteead of token. It is type constrained by the data we receive from third-party-capital

**Comment by harlan-zw** [comment]
Is there a reason why you thought it was `token` instead of `id`? The [docs](https://scripts.nuxt.com/scripts/tracking/google-tag-manager) should be clear but maybe I'm missing something?

**Comment by Kronhyx** [comment]
https://scripts.nuxt.com/scripts/tracking/google-tag-manager
![image](https://github.com/user-attachments/assets/19dc3100-b3f4-4e27-91fd-2d02b0e1a163)

@harlan-zw @huang-julien ..

i can create a PR  to change it if you want

**Comment by harlan-zw** [comment]
Sure a PR would be great :)
