### ISSUE TITLE
Two or more GTM containers

### ISSUE THREAD

**Issue by konstantin-karlovich-unbiased-co-uk** [nuxt/scripts#154]
@harlan-zw hi!

I may have missed it somewhere, although I've gone through the documentation completely.
Can you please tell me if it is possible to add two or more GTM containers?
If so, how do I use them?

In brief - I need to use different gtm-id on different url's. And the GTM script should be loaded immediately, by default

**Comment by harlan-zw** [comment]
@konstantin-karlovich-unbiased-co-uk Can you provide some more technical guidelines around how you'd normally implement this? Do you rename the `dataLayer` object?

Nuxt Scripts supports loading the same script multiple times by modifying the key, however, it does not support modifying the `dataLayer` window key.

```ts
const { dataLayer, $script } = useScriptGoogleTagManager({
  id: 'G-TR58L0EF8P',
})

const { dataLayer: dataLayer2, $script: $script2 } = useScriptGoogleTagManager({
  key: 'gtm2',
  id: 'G-1234567890',
})
```

@huang-julien, @flashdesignory do you have any thoughts on being able to set the `dataLayer` key? It seems quite difficult to do with the TPC templating.

**Comment by flashdesignory** [comment]
Would it help if we'd accept a `dataLayer` name, in addition to the `id` here?
https://github.com/GoogleChromeLabs/third-party-capital/blob/main/src/third-parties/google-analytics/data.json#L15

**Comment by harlan-zw** [comment]
Seems reasonable if we're doing that for `id` currently

**Comment by harlan-zw** [comment]
> I did this example, but the container was connected only during the call of the tracking method, which is not quite suitable for me

I'm not too sure what you mean, both scripts will start loading by default once Nuxt is partially hydrated. GTM is designed to handle this as events are batched to be sent one the script is loaded and the page is idle.

**Comment by flashdesignory** [comment]
@harlan-zw - something like this should work:
https://github.com/GoogleChromeLabs/third-party-capital/pull/52

**Comment by harlan-zw** [comment]
You should use the globals if you want to load the script immediately.

```ts
export default defineNuxtConfig({
  scripts: {
    registry: {
      googleAnalytics: {
        id: 'YOUR_ID'
      }
    }
  }
})
```

Then in your component, you should be able to do

```
const { gtag} = useNuxtApp().$scripts.googleAnalytics
// gtag(...)
```

We'll improve the docs around this.

The issue as raised was about allowing you to embed multiple GTM / GA containers without conflict so we'll close this once https://github.com/nuxt/scripts/pull/163 is available in a release.
