### ISSUE TITLE
Hook for scripts being loaded

### ISSUE THREAD

**Issue by joachimhviid** [nuxt/scripts#160]
It would be helpful to be able to react to a script getting loaded. Currently the module has a `scripts:updated` hook that can be used for searching for the loaded event, but it is will be inefficient to iterate through the events to find the 'loaded' event, every time there is an update.
Instead I propose a `scripts:loaded` hook that will be called once when the script reaches that status. This allows the developer to react to the specific event and run some logic in response. For instance, you might want to run a consent update or a custom event once a script has been loaded via a consent banner.
An example implementation could look something like the following inside the `useScript` composable:
```ts
head.hooks.hook('script:updated', (ctx) => {
  if (ctx.script.id !== instance.$script.id)
    return
  if (ctx.script.status === 'loaded') {
    nuxtApp.callHook('scripts:loaded', { [ctx.script.id]: true })
  }
  // convert the status to a timestamp
  payload.events.push({
    type: 'status',
    status: ctx.script.status,
    at: Date.now(),
  })
  payload.$script = instance.$script
  syncScripts()
})
```

**Comment by harlan-zw** [comment]
Hi @joachimhviid 

Thanks for the issue. I think maybe the docs aren't clear as `useScript` is designed to expose this really simply, you shouldn't need to use these hooks, they're for internal uses.

```ts
const { $script } = useScript('/script.js')

// Option 1: The $script object is a promise that resolves when the script is loaded
$script.then(() => {
  // script is loaded!
})

// Option 2: Watch the script status
watch($script.status, (status) => {
  if (status === 'loaded') {
   // do something
  }
})
```

Maybe the [Unhead useScript docs](https://unhead.unjs.io/usage/composables/use-script#waiting-for-script-load) are clearer.

Let me know if any of that isn't clear either way.

**Comment by joachimhviid** [comment]
Thanks for clearing it up. That approach worked great, thanks! 
I've really enjoyed using the module so far, I'm looking forwards to the full release.
