### ISSUE TITLE
Add Microsoft UET to registry

### ISSUE THREAD

**Issue by joachimhviid** [nuxt/scripts#165]
Script can be found [here](https://help.ads.microsoft.com/#apex/ads/en/56686/2-500)

I attempted to implement it myself like below, but I am running into problems with UET not being available from the script that is being set, since it is part of the script being loaded.
```ts
const { uetq, $script } = useRegistryScript('bing', () => ({
  scriptInput: {
    src: 'https://bat.bing.com/bat.js',
    async: true,
    crossorigin: false,
  },
  scriptOptions: {
    use() {
      return { uetq: window.uetq }
    },
  },
  clientInit: import.meta.server
    ? undefined
    : () => {
        window.uetq = window.uetq || []

        const options = { ti: 'YOUR_KEY_HERE', enableAutoSpaTracking: true }
        // @ts-expect-error untyped
        options.queue = window.uetq
        // @ts-expect-error untyped
        window.uetq = new UET(options)

        window.uetq.push('consent', 'default', { ad_storage: 'denied' })
      },
}))
```

The original script creates a brand new script element with `https://bat.bing.com/bat.js` as the source and then sets the window.uetq from there, but I am unsure how to recreate that in a registry script.

**Comment by harlan-zw** [comment]
Hey, I'll leave this issue open to discuss the issues you're running into but would you mind also posting this integration in https://github.com/nuxt/scripts/discussions/177.


Thanks!

**Comment by joachimhviid** [comment]
Posting my workaround from #177 in here as well. The following worked for me, but unfortunately only through the $script object.

```ts
const { $script } = useScript(
  {
    src: 'https://bat.bing.com/bat.js',
    crossorigin: false,
  },
  {
    use() {
      return { uetq: window.uetq }
    },
  },
)

watch($script.status, (status) => {
  if (status === 'loaded') {
    const options = { ti: 'TAG_ID_HERE', enableAutoSpaTracking: true }
    // @ts-expect-error untyped
    options.q = window.uetq
    // @ts-expect-error untyped
    window.uetq = new UET(options)
  }
})
```

**Comment by harlan-zw** [comment]
Slight DX on the loading improvement. I'll look at the other issues when I next do a round of 3p scripts. Will close for now in favour of the item on https://github.com/nuxt/scripts/discussions/177

```ts
const { onLoaded } = useScript(
  {
    src: 'https://bat.bing.com/bat.js',
    crossorigin: false,
  },
  {
    use() {
      return { uetq: window.uetq }
    },
  },
)

onLoaded((uetq) => {
    const options = { ti: 'TAG_ID_HERE', enableAutoSpaTracking: true }
    // @ts-expect-error untyped
    options.q = uetq
    // @ts-expect-error untyped
    window.uetq = new UET(options)
})
```
