### ISSUE TITLE
Failed to parse static properties from plugin

### ISSUE THREAD

**Issue by yoji-kojio** [nuxt/scripts#175]
Hey guys!
I am configuring my Nuxt 3 project to use the Hotjar and Google Analytics script using @nuxt/scripts, adding the script in my nuxt.config.ts exactly as the documentation says:

```javascript
export default defineNuxtConfig({
  scripts: {
    registry: {
      hotjar: {
        id: 1234567
      }
    }
  }
})
```

However, I am receiving the following warning on console:

```console
WARN  Failed to parse static properties from plugin .nuxt/modules/@nuxt-scripts.mjs. ENOENT: no such file or directory, open '/home/user/Workspace/project/.nuxt/modules/@nuxt-scripts.mjs'

at async open (node:internal/fs/promises:633:25)
at async Object.readFile (node:internal/fs/promises:1242:14)
at async annotatePlugins (node_modules/nuxt/dist/index.mjs:4873:68)
at async getContents (node_modules/nuxt/dist/index.mjs:4396:27)
at async i.getContents (node_modules/@nuxt/devtools/dist/chunks/plugin-metrics.mjs:10:23)
at async node_modules/nuxt/dist/index.mjs:4744:22
at async Promise.allSettled (index 16)
at async generateApp (node_modules/nuxt/dist/index.mjs:4740:3)
at async _applyPromised (node_modules/perfect-debounce/dist/index.mjs:54:10)
```

I see that the Hotjar script is being correctly inserted into my page, but the warning is still being displayed. Should I be worried?
The same error is ocurring on Google Analytics script too.

I checked a [issue](https://github.com/nuxt/scripts/issues/121) with the same warning, and the problem was about the use of functions to setup data on nuxt.config.ts, but that's not my case.

Versions:
```
@nuxt-scripts: 0.6.4
nuxt: 3.11.2
```

**Comment by harlan-zw** [comment]
Hi, could you please try this with the latest Nuxt version (3.12.4), I think this was fixed upstream as I haven't been able to replicate it in a while.

**Comment by yoji-kojio** [comment]
> Hi, could you please try this with the latest Nuxt version (3.12.4), I think this was fixed upstream as I haven't been able to replicate it in a while.
> 
> Either way it is safe to ignore

that's it! updated nuxt version and the warning is gone! thanks @harlan-zw ! :smile_cat:
