### ISSUE TITLE
fix: GoogleTagManager default key case missmatch

### ISSUE THREAD

**Issue by Ask1n** [nuxt/scripts#179]
### 🐛 The bug

[Example from docs](https://scripts.nuxt.com/scripts/tracking/google-tag-manager#example) does not work 

Because useRegistryScript doesn't get gtm id from useRuntimeConfig

https://github.com/nuxt/scripts/blob/3c8838558debe268861e33e8a5abba02523aa36e/src/runtime/utils.ts#L35-L37

default key "google-tag-manager" but useRuntimeConfig().public.scripts has "googleTagManager"
https://github.com/nuxt/scripts/blob/3c8838558debe268861e33e8a5abba02523aa36e/src/runtime/registry/google-tag-manager.ts#L18-L18

### 🛠️ To reproduce

^

### 🌈 Expected behavior

expected that useScriptGoogleTagManager() gets gtm id from config

**Comment by Ask1n** [comment]
this seems to only happen when using environment variables 🤔

I also noticed that if you specify key then the icon is displayed in devtools
```js
useScriptGoogleTagManager({
  key: 'googleTagManager',
})
```

![изображение](https://github.com/user-attachments/assets/fec985b0-8278-439a-af2e-85e662329f87)

**Comment by harlan-zw** [comment]
Hi, thank you for reporting this. This should be fixed in the next version.
