### ISSUE TITLE
 useScriptGoogleAnalytics is not sending events 

### ISSUE THREAD

**Issue by Codethier** [nuxt/scripts#184]
### 🐛 The bug

```
const { gtag, $script } = useScriptGoogleAnalytics({
  id: 'G-XXXXXXX'
})

gtag('event', 'conversion-test2')
```

The following code does not show up in analytics, neither as event event nor in the realtime dashboard, based on the docs  nothing else needs to be done. 

I've tried setting the usual things, 
```
 gtag('js', new Date());
 gtag('config', 'G-XXXXXX')
```
But these are properly set already in the data layer so there is no need for that.

screens from tag assistant:

![image](https://github.com/user-attachments/assets/8aca9048-5da0-4506-ab43-72450405df7b)
![image](https://github.com/user-attachments/assets/6bf9793f-64ae-4459-99d9-64669698bac6)

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-g9nj6p?file=pages%2Findex.vue

### 🌈 Expected behavior

Analytic events should be sent

**Comment by harlan-zw** [comment]
cc: @huang-julien @flashdesignory
