### ISSUE TITLE
googlemaps latlng

### ISSUE THREAD

**Issue by Alidkhh** [nuxt/scripts#187]
### 📚 What are you trying to do?

i use ScriptGoogleMaps component and i want to use LatLng object for set marker in google maps .
i tried to pass this object to options.center and query but its not working.
Am I using it wrong ?

**Comment by Ulrich-Mbouna** [comment]
Hello,

I'm also confused how to set query correctly in that component.

**Comment by Alidkhh** [comment]
hi
i tried to use this component like this but its not working , am i using it wrong?
<ScriptGoogleMaps :query="{ lat: -34.397, lng: 150.644 }" :api-key="apiKey" :options="googleMapOptions" />
<ScriptGoogleMaps query="{ lat: -34.397, lng: 150.644 }" :api-key="apiKey" :options="googleMapOptions" />

**Comment by Ulrich-Mbouna** [comment]
Using object syntax didn't work. I use string for query (Town or quarter).

**Comment by harlan-zw** [comment]
Please refer to the new `markers` prop in this PR https://github.com/nuxt/scripts/pull/191, should be stable as of 0.7.1
