### ISSUE TITLE
Scripts loaded depending on "device"

### ISSUE THREAD

**Issue by oritwoen** [nuxt/scripts#194]
### 🆒 Your use case

Depending on the type of device or browser agent, some scripts are not needed and only affect the results, e.g. in pagespeed negatively.

In the example below, I created a code that loads analytical scripts only if the user agent is not a crawler. I used the `@nuxtjs/device` module for this

```js
const { isCrawler } = useDevice()

if (!isCrawler) {
	useScriptXPixel({ id: 'xx' })
	useScriptClarity({ id: 'xx' })
	useScriptMetaPixel({ id: 'xx' })
	useScriptGoogleAnalytics({ id: 'G-xx' })
	useScriptCloudflareWebAnalytics({ token: 'xx' })

	useScript('https://cdn.xx.net/storage/xx/client.js', {
		bundle: true,
	})
}

```

### 🆕 The solution you'd like

It would be nice to have a direct option to load scripts depending on the device based on:

```js
useScript('https://scripts.com/script.js', {
	device: 'desktop|mobile'
})
```

**Comment by harlan-zw** [comment]
Hi, thanks for the issue.

Nuxt Scripts is made for this type of scenario. In this instance, your best bet would be to set a manual trigger for composables that you don't want to load.

```ts
useScriptXPixel({ 
     id: 'xx', 
     scriptOptions: isCrawler ? 'manual' : 'onNuxtReady'
})
```

Alternatively you can have it as manual and call the load function manually.


```ts
const { $script } = useScriptXPixel({ 
     id: 'xx', 
     scriptOptions: 'manual'
})

if (!isCrawler) {
  $script.load()
}
```

**Comment by oritwoen** [comment]
Thanks for the answer @harlan-zw. Indeed the solutions you show and the scenario are the most simple and effective.

Thanks again for showing an effective example and possibilities.
