### ISSUE TITLE
Add Sentry as a supported Script Registry script

### ISSUE THREAD

**Issue by nathanchase** [nuxt/scripts#209]
@manniL had [a great primer on integrating Sentry into your Nuxt 3 app](https://www.lichter.io/articles/nuxt3-sentry-recipe/#nuxt-integration-setting-up-the-client-side), but perhaps there's an opportunity to create a Sentry composable or other similar implementation for [Sentry](https://sentry.io/)?

It might be better suited as a module since there is an entirely separate server-side to account for, but [nuxt/scripts](https://github.com/nuxt/scripts) feels like a natural place people will be looking for a Sentry solution.

**Comment by manniL** [comment]
Hmm - maybe this should be integrated via their own SDK "using" nuxt scripts (if the module is installed) https://github.com/getsentry/sentry-javascript/issues/9095

**Comment by harlan-zw** [comment]
I would agree that the official SDK for Nuxt should be used. 

As Nuxt Scripts is only about loaded remote third-party scripts, if there's a NPM module available, it's likely that Nuxt Scripts isn't the right solution.
