### ISSUE TITLE
Blog: Example does not work after tab switch

### ISSUE THREAD

**Issue by manniL** [nuxt/scripts#212]
### 🐛 The bug

Also shown in the video below from 00:06 on (before just a sanity check that it works).

1. Go to https://nuxt.com/blog/nuxt-scripts
2. Scroll to the YouTube example
3. DO NOT click the video yet
4. Click on "input"
5. Click on "output" again
6. Try to play the video
7. See that it doesn't work

[nuxt-blog-scripts.webm](https://github.com/user-attachments/assets/d92655a4-6c95-495d-b33c-35797a180e7e)

### 🛠️ To reproduce

https://nuxt.com/blog/nuxt-scripts

### 🌈 Expected behavior

The video should be loaded after the click too

**Comment by harlan-zw** [comment]
Thanks for the issue and reproduction details. 

This will be fixed in 0.7.2 which will be released shortly.
