### ISSUE TITLE
DNS prefetch / preload default triggered scripts

### ISSUE THREAD

**Issue by harlan-zw** [nuxt/scripts#218]
### 🆒 Your use case

For scripts using the default trigger (onNuxtReady) we should probably do a prefetch or preload so that the script is downloaded and executated as quickly as possible.

### 🆕 The solution you'd like

-

**Comment by infabo** [comment]
Using https://scripts.nuxt.com/scripts/tracking/google-tag-manager

```html
<link rel="preload" as="script" href="https://www.googletagmanager.com/gtm.js" crossorigin="anonymous" fetchpriority="low" data-hid="07ee526">
```

This should not be preloaded. https://www.googletagmanager.com/gtm.js can't be called without `id` query parameter.

**Comment by harlan-zw** [comment]
I think this was a bug related to using globally registered GTM and the composable which I pushed up a fix for. 

If the latest version doesn't fix that please provide a reproduction and I'll get to the bottom of it.
