### ISSUE TITLE
A working example for best practices using Google Analytics

### ISSUE THREAD

**Issue by ronenteva** [nuxt/scripts#227]
### 📚 Is your documentation request related to a problem?

It seems that there are many of using `useScriptGoogleAnalytics`: `$script, proxy, gtag, dataLayer, dataLayers.default`.
I think it will be very useful to have a working example for best practices.

**Comment by harlan-zw** [comment]
Hi, for Google Analytics I'd suggest using it as you would normally but use the proxy for everything. I've added the following to the docs, let me know if it's not clear.

### Usage

To interact with the Google Analytics API, it's recommended to use the script [proxy](/docs/guides/key-concepts#understanding-proxied-functions).

```ts
const { proxy } = useScriptGoogleAnalytics()

proxy.gtag('event', 'page_view')
```

The proxy exposes the `gtag` and `dataLayer` properties, and you should use them following Google Analytics best practices.
