### ISSUE TITLE
Landing page shows 0 contributors

### ISSUE THREAD

**Issue by manniL** [nuxt/scripts#229]
![image](https://github.com/user-attachments/assets/0fc209cd-726f-4b4f-bd89-6f9fcff8bef2)

**Comment by harlan-zw** [comment]
Thanks, seems the Nuxt API was down or rate-limited when the docs were last generated :thinking: Working now.

![image](https://github.com/user-attachments/assets/43a4fdac-2c16-4fd7-a5a1-75f1b940bb20)

I'll push up a fix to fail the build if the API is down.
