### ISSUE TITLE
bundle from local npm instead of external unpkg.com to prevent connection error

### ISSUE THREAD

**Issue by andrewspy** [nuxt/scripts#233]
### 🆒 Your use case

I had an occasion during build, where a connection error occurred when fetching from unpkg.com, and the bundled script became an error HTML instead of javascript.

(See additional info)

### 🆕 The solution you'd like

Bundle from local npm/pnpm, which is much more secure in my opinion.

### 🔍 Alternatives you've considered

Alternatively, stop the build if there is a connection error.

### ℹ️ Additional info

```
[@nuxt/scripts 11:06:17 AM]   ├─ https://unpkg.com/pannellum@2.5.6/build/pannellum.js → /_scripts/pjUWCueFMU.js (0.00 kB br)
```

html of the error in the bundle script

![_C__Users_admin_Downloads_pjUWCueFMU html](https://github.com/user-attachments/assets/54b54846-fadb-4b63-a318-d584b246e466)

**Comment by harlan-zw** [comment]
Hmm but the dependency won't be in your node_modules as it's only runtime downloaded as an IIFE script?

I think failing the build if the script can't be downloaded makes sense though, or at least it should fallback to not bundling.

**Comment by andrewspy** [comment]
@harlan-zw I think giving a warning during the build process and fallback to not bundling is a better way to go. At least the script doesn't break the app in the event there is a connection error.

**Comment by huang-julien** [comment]
I'm not sure about the no bundling fallback. Most users in EU will probably want to bundle to avoid issues with the GDPR regulation.
The warning will be drowned into the tons of file results logs of nitro. I think it's probably better to throw as suggested by @harlan-zw

**Comment by huang-julien** [comment]
We could also add a new option in a minor to opt-in the fallback behaviour

**Comment by harlan-zw** [comment]
Sounds good to me, thanks!
