### ISSUE TITLE
Google Ads

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [nuxt/scripts#269]
### 🆒 Your use case

I use Google Ads to track conversions

### 🆕 The solution you'd like

Something similar to Facebook Pixel or Google Tag Manager

### ℹ️ Additional info

Site: ads.google.com

**Comment by harlan-zw** [comment]
Can you link docs for the tracker?

**Comment by diego-lipinski-de-castro** [comment]
Hello, maybe it will not be necessary to add a different lib, because it seems to be the case that google is saying to just use the tag manager to track events from AdWords for example, I will link a few pages just in case.

[GoogleAds 1](https://support.google.com/google-ads/answer/7548399?hl=en)
[GoogleAds 2](https://support.google.com/google-ads/answer/12215519?hl=en&ref_topic=12215426&sjid=9801818615584708699-SA#zippy=%2Cin-google-ads%2Cin-google-analytics%2Cin-campaign-manager%2Cin-google-tag-manager%2Coption-set-up-the-google-tag-for-your-website%2Coption-use-google-tag-manager%2Cuse-the-google-tag-found-on-your-website-recommended%2Cinstall-a-google-tag)
[GoogleAds 3](https://support.google.com/google-ads/answer/6331314?sjid=9801818615584708699-SA#zippy=%2Cset-up-conversion-tracking-using-the-google-tag%2Ccheck-your-conversion-tracking-tag)
[GoogleAds 4](https://developers.google.com/tag-platform/devguides/conversions?hl=pt-br)
[Stackoverflow about google ads](https://stackoverflow.com/questions/25186071/google-adwords-conversion-tracking-event-single-page)

It seems they are saying to using something like 
```javascript
gtag('event',  'conversion',  {
    'send_to': 'AW-CONVERSION_ID/AW-CONVERSION_LABEL',
    'value': 1.0,
    'currency': 'USD'
});
```

Instead of 
```javascript
<!-- Put this script in your <head> -->
<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion_async.js" charset="utf-8"></script>

<!-- the rest of your web page as usual etc -->

<!-- Call this function when the form submits -->
<script type="text/javascript">
/* <![CDATA[ */
window.google_trackConversion({
    google_conversion_id: 123456789, 
    google_conversion_label: abcdefghijkl,  // if provided, remove this line if not provided
    google_conversion_value: 0,  // or the dollar value of this conversion, e.g. 100 etc.
    google_remarketing_only: false
});
//]]>
```

But, to be honest, I am still confused if they are the same thing

**Comment by diego-lipinski-de-castro** [comment]
Closing this
