### ISSUE TITLE
No performance gain using GTM / Google Analytics

### ISSUE THREAD

**Issue by ejerskov** [nuxt/scripts#272]
### 📚 What are you trying to do?

As I understand it, @nuxt/script should give better performance using the embedded third-party scripts.

However when I use GTM or GoogleAnalytics I see the same hit in PageSpeed reports as using the "vanilla" scripts:
![image](https://github.com/user-attachments/assets/606f0734-3710-4bcd-b886-9a3da088a471)

I've done the simple implementation of adding this in my App.vue:
GTM:
```
useScriptGoogleTagManager({
  id: 'GTM-WHHKRNTJ',
})
```

Google Analytics:
```
useScriptGoogleAnalytics({
  id: 'G-0HXKBMGTW0',
})
```

Have I misunderstood the concept of this package?

**Comment by melasculla** [comment]
![image](https://github.com/user-attachments/assets/6f635ee4-5a8a-4715-a070-649cda33c84a)

![image](https://github.com/user-attachments/assets/e953efa4-c951-4e5d-9f94-0b57b21c37d4)

for me the same

`$production: {
    scripts: {
      registry: {
        googleTagManager: {
          scriptOptions: {
            tagPosition: 'bodyClose',
          },
          id: 'G-8798ZQP3DJ',
        }
      }
    }
  }`

**Comment by harlan-zw** [comment]
Hi, thanks for the issue. You should understand that Nuxt Scripts's performance optimizations are micro at best, they just allow Nuxt to start before loading in other scripts. 

The fact is you're still  loading in 104kb of scripts just for GTM, for reference Nuxt itself is only like ~50kb iirc.

My suggestion is to drop GTM if you're only using it as a container for GA, then wait for either one of these that will provide significant improvements:
- https://github.com/nuxt/scripts/issues/87
- https://github.com/nuxt/scripts/issues/182

**Comment by ejerskov** [comment]
Ok, thanks for clearing that up @harlan-zw.

I ended up implementing partytown instead of @nuxt/scripts but will look forward to it being embedded.

**Comment by awdr74100** [comment]
@ejerskov  Can you tell me the specific implementation details of partytown? As far as I know, `@nuxtjs/partytown` has a lot of bugs.
