### ISSUE TITLE
Matomo does not work with a cloud url

### ISSUE THREAD

**Issue by kaboume** [nuxt/scripts#279]
### 🐛 The bug

In my application, I have Analytics tracking working correctly however it does not work for Matomo.
Is it because I use matomo cloud?

Her is my nuxt.config.ts file : 
```
scripts: {
    registry: {
      googleAnalytics: {
        id: "G-XXXXXXXX",
      },
      matomoAnalytics: {
        matomoUrl: "https://[mydomain].matomo.cloud/",
        siteId: "2",
      },
    },
  },

```
### 🛠️ To reproduce

no

### 🌈 Expected behavior

no

**Comment by roiLeo** [comment]
> I took a look at the Matomo implementation and doc and it did need some work. 

There's still something strange going on with self-hosted matomo.

note: It's working fine on version [v.0.6.2](https://github.com/nuxt/scripts/releases/tag/v0.6.2)

**Comment by harlan-zw** [comment]
Can you provide some more details?

**Comment by roiLeo** [comment]
> Can you provide some more details?

When I develop locally and use the current version, I get no data on my self-hosted Matomo. But when I use version v0.6.2, I get real time data.

same code
```
const test = useScriptMatomoAnalytics({
  matomoUrl: 'https://custom-domain.com',
  siteId: 'x',
  trackPageView: true
})
```

I've tried to setup inside nuxt.config, and change siteId to number but it's still not working.
