### ISSUE TITLE
Allow for more granular control over preloading scripts

### ISSUE THREAD

**Issue by Ingramz** [nuxt/scripts#294]
### 🆒 Your use case

Currently when a consent trigger or a manual trigger is used to load a script, the `rel=preload` tag becomes a `rel=preconnect`, in privacy sensitive situations leaking the IP address by preconnecting may be undesirable and we want total control over the way when we want the user's browser to connect to a server hosting a script.

On the other hand there may be also situations where we are fine with preloading the script for the user, but we want to delay the evaluating of that script to the last possible moment. This means there also exists a combination where manual trigger and `rel=preload` can be desirable.

In consent-based triggers, we may want a combination of both depending on the consent given. For instance, when we have already collected consent from the user, we can start including `rel=preload` in head at the server side and before that we should not be loading anything.

### 🆕 The solution you'd like

I think it's difficult to outline a solution that would surely work for everyone, at least without giving it some additional thought. But at the moment I feel that it is too difficult to control the preloading behavior if the default behavior for some reason is not suitable.

Since my main use case involves triggering on consent, I may be currently too blind to see other valid cases where preloading may be wanted to be controlled differently from the default. Perhaps this is where insight from others may also be helpful and I hope that at least by starting a discussion, a more flexible solution can be worked towards.

**Comment by harlan-zw** [comment]
Thank you for this detailed issue. I've made an effort to solve this here https://github.com/nuxt/scripts/pull/302

In it, we no longer warm up origins/scripts if a non-immediate trigger has been provided and provide an API around warming up for more advanced use cases.

**Comment by Ingramz** [comment]
Looking good, is there any way I can easily preview this before release?

**Comment by harlan-zw** [comment]
Hmm seems like the nightly's aren't actually deploying 🤡

**Comment by Ingramz** [comment]
Overall it seems to be working great. Documentation saying `warmupStrategy` can be a function does not seem to hold true though. In my case I could determine the desired value ahead of time and pass it as an option directly instead.

Also thank you for reacting so quickly, overall both the option and function feel very easy to use and complements rest of the package very well.
