### ISSUE TITLE
Registry scripts `scriptInput` shows a type error when trying to disable `crossorigin` or `referrerpolicy`

### ISSUE THREAD

**Issue by Ingramz** [nuxt/scripts#305]
### 🐛 The bug

While investigating a regression in GTM possibly caused by script attribute defaults, I noticed that disabling `crossorigin` and `referrerpolicy` results in type errors being displayed.

```ts
useScriptGoogleTagManager({
  id: 'GTM-123456',
  scriptInput: {
    async: true,
    defer: false,
    crossorigin: false, // type error
    referrerpolicy: false, // type error
  },
})
```

This seems be apply universally to all registry scripts.

### 🛠️ To reproduce

N/A

### 🌈 Expected behavior

Registry scripts `scriptInput` should accept falsy values the same way as in `useScript`.

**Comment by harlan-zw** [comment]
This one was solved afaik.

**Comment by Ingramz** [comment]
Doesn't look like it. The [`ScriptInput` type for `RegistryScriptInput`](https://github.com/nuxt/scripts/blob/7e1477ce140428a6e80a0f835c94b1828f6c06ec/src/runtime/types.ts#L169) doesn't wrap equivalent of `MaybeComputedRefEntriesOnly` that can be found at [plain `useScript`](https://github.com/unjs/unhead/blob/cbd82c932496c84b0093f7891ab12922e7d1b4af/packages/vue/src/composables/useScript.ts#L24).
