### ISSUE TITLE
Type Checking Bug

### ISSUE THREAD

**Issue by harlan-zw** [nuxt/scripts#312]
### 🐛 The bug

![Image](https://github.com/user-attachments/assets/0b0e12f0-d164-4548-87b3-72335a63fc64)

### 🛠️ To reproduce

-

### 🌈 Expected behavior

-

**Comment by LePtiDev** [comment]
Same issue for me 👍

**Comment by LePtiDev** [comment]
When you run command: `pnpm exec nuxi typecheck`
My nuxt config: 

```
// https://nuxt.com/docs/api/configuration/nuxt-config
import { defineNuxtConfig } from 'nuxt/config';
import packageJson from './package.json';

export default defineNuxtConfig({
  ssr: false,
  devtools: {
    enabled: true,
    componentInspector: false,
  },
  app: {
    head: {
      title: `NRJx - ${packageJson.version}`,
      meta: [
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { 'http-equiv': 'cache-control', content: 'max-age=0' },
        { 'http-equiv': 'cache-control', content: 'no-cache' },
        { 'http-equiv': 'expires', content: '0' },
        { 'http-equiv': 'expires', content: 'Tue, 01 Jan 1980 1:00:00 GMT' },
        { 'http-equiv': 'pragma', content: 'no-cache' },
      ],
    },
  },
  telemetry: false,
  compatibilityDate: '2024-09-05',
  future: {
    compatibilityVersion: 4,
  },
  nitro: {
    preset: 'cloudflare_pages',
    prerender: {
      autoSubfolderIndex: false,
    },
  },
  router: {
    options: {
      scrollBehaviorType: 'smooth',
    },
  },
  sourcemap: { client: true },
  sentry: {
    sourceMapsUploadOptions: {
      org: 'nrjx-wl',
      project: process.env.NUXT_PUBLIC_SENTRY_PROJECT,
      authToken: process.env.NUXT_PUBLIC_SENTRY_AUTH_TOKEN,
    },
  },
  modules: ['@pinia/nuxt', '@nuxt/scripts', '@nuxt/eslint', '@nuxtjs/tailwindcss', '@sentry/nuxt/module'],
  scripts: {
    registry: {
      segment: true,
    },
  },
  imports: {
    dirs: ['composables/**', 'stores/**', 'app-modules/**/stores/**', 'app-modules/**/composables/**'],
  },
  typescript: {
    typeCheck: false,
    strict: false,
  },
  tailwindcss: {
    viewer: false,
    cssPath: ['./app/main.css', { injectPosition: 'first' }],
    configPath: 'tailwind.config',
  },
  pinia: {
    storesDirs: ['./app/stores/**', './app/app-modules/**/stores/**'],
  },
  runtimeConfig: {
    public: {
      graphqlUrl: '',
      backendUrl: '',
      apiV2Url: '',
      firebase: {
        apiKey: '',
        authDomain: '',
        projectId: '',
        storageBucket: '',
        messagingSenderId: '',
        appId: '',
      },
      sentry: {
        dsn: '',
        authToken: '',
        project: '',
        environment: '',
      },
      scripts: {
        segment: {
          writeKey: '',
          analyticsKey: '',
        },
      },
    },
  },
});
```


You have console error about your node module like this: 

`     2  ../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.6.0_@vue+compiler-core@3.5.13_axios@1.7.7_nuxt@3.14.1592_c3xkt4s2hxdzrnvdwi5abfpeom/node_modules/@nuxt/scripts/dist/runtime/components/ScriptCarbonAds.vue:4
     2  ../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.6.0_@vue+compiler-core@3.5.13_axios@1.7.7_nuxt@3.14.1592_c3xkt4s2hxdzrnvdwi5abfpeom/node_modules/@nuxt/scripts/dist/runtime/components/ScriptCrisp.vue:4
     2  ../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.6.0_@vue+compiler-core@3.5.13_axios@1.7.7_nuxt@3.14.1592_c3xkt4s2hxdzrnvdwi5abfpeom/node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleAdsense.vue:4
     1  ../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.6.0_@vue+compiler-core@3.5.13_axios@1.7.7_nuxt@3.14.1592_c3xkt4s2hxdzrnvdwi5abfpeom/node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue:13
     3  ../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.6.0_@vue+compiler-core@3.5.13_axios@1.7.7_nuxt@3.14.1592_c3xkt4s2hxdzrnvdwi5abfpeom/node_modules/@nuxt/scripts/dist/runtime/components/ScriptIntercom.vue:4
     1  ../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.6.0_@vue+compiler-core@3.5.13_axios@1.7.7_nuxt@3.14.1592_c3xkt4s2hxdzrnvdwi5abfpeom/node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezy.vue:6
     1  ../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.6.0_@vue+compiler-core@3.5.13_axios@1.7.7_nuxt@3.14.1592_c3xkt4s2hxdzrnvdwi5abfpeom/node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue:2
     1  ../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.6.0_@vue+compiler-core@3.5.13_axios@1.7.7_nuxt@3.14.1592_c3xkt4s2hxdzrnvdwi5abfpeom/node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue:6
     1  ../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.6.0_@vue+compiler-core@3.5.13_axios@1.7.7_nuxt@3.14.1592_c3xkt4s2hxdzrnvdwi5abfpeom/node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue:9
     1  ../../node_modules/.pnpm/@nuxt+scripts@0.9.5_@nuxt+devtools@1.6.0_@vue+compiler-core@3.5.13_axios@1.7.7_nuxt@3.14.1592_c3xkt4s2hxdzrnvdwi5abfpeom/node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue:9`

**Comment by huang-julien** [comment]
Hey :wave: can you provide reproductions instead of pieces of code ?

Seems like this is a build issue, probably within the module itself

**Comment by harlan-zw** [comment]
Going to close this as I think this was solved, needs more context anyway. I believe I just dumped this from my Discord
