### ISSUE TITLE
Wrong Types for gtag function params

### ISSUE THREAD

**Issue by mod08** [nuxt/scripts#320]
### 🐛 The bug

The tuple type for the gtag function params contains only `[fn: 'config', opt: 'reset']` which is the last definition in the GTag interface from the library 'third-party-capital'. 

I wasn't able to reproduce it in stackblitz because the types didn't work at all. I've testet in the nuxt-script Playground. 

![Image](https://github.com/user-attachments/assets/976bef33-4d68-4639-acd5-ec238bfaeec4)

### 🛠️ To reproduce

- 

### 🌈 Expected behavior

Infer the correct types based on the first argument of the function.

**Comment by KieronWiltshire** [comment]
I'm also getting this issue
