### ISSUE TITLE
Duplicate "onLoaded" for Singleton Pattern

### ISSUE THREAD

**Issue by kbarnesMCC** [nuxt/scripts#330]
### 📚 What are you trying to do?

I have a Vue component that loads a 3rd party script with `useScript`. This script adds it's interface to the `window` of the page and upon the script being loaded I need to invoke one of it's methods immediate (e.g. initialization of the script).

I've been able to do this by leverage the `onLoaded` return from `useScript` to then access `window` and invoke the method just fine.

However, when my Vue component has multiple instances in the page; the `onLoaded` is executed multiple times; once for each component. The net effect is that the initialization routine of the 3rd party scripts runs multiple times; once for each instance of the components.

I suspect I'm misunderstanding something about the singleton pattern; I can confirm only a single `script` tag is injected despite the presence of multiple `useScript` calls on the page (e.g. multiple vue components). Perhaps there's another approach I'm supposed to take to scaffold this?

Note that I cannot use a "Global" approach here as only some pages on my site would have these Vue components.

### 🔍 What have you tried?

I'm tried to see if there's a reliable way to detect which Vue component instance I'm in within my `onLoaded` callback; theory was to simply only do the initialization methods on "index 0" or equivalent. Unfortunately, I haven't been able to find how to add such details to the `onLoaded` callback.

**Comment by harlan-zw** [comment]
Hi, there are many solutions here. I can provide the most help if you tell me which third party you're integrating.

One option would be to register the script in a Nuxt plugin with a manual trigger and a single `onLoaded` then within your components, you would simply trigger the load. I may consider adding in a `onLoadedSingleton` function if there's a valid use case.

```ts
// plugins/script.ts
import { useScriptFoo } from "~/utils/scripts";

export default defineNuxtPlugin({
  setup() {
    const { onLoaded } = useScriptFoo()
    onLoaded(() => {
      // do something
    })
  }
})
```

```ts
//utils/script.ts
export function useScriptFoo() {
  return useScript('https://cdn.jsdelivr.net/npm/foo@1.2.3/dist/foo.js', {
    trigger: 'manual'
  })
}
```

```vue
<script lang="ts" setup>
import { useScriptFoo} from '~/utils/scripts'

const { onLoaded, load } = useScriptFoo()
load() // load the script
onLoaded(() => {
  // do component specific stuff (if applicable)
})
</script>
```

**Comment by kbarnesMCC** [comment]
In my case, I'm integrating [HTL BID](https://docs.hashtag-labs.com/htl-bid-guide/installing-the-code) as our primary advertising stack. In essence we setup specifically-attributed `<div>`s throughout our page and then invoke `window.htlbid.layout()` after their script has loaded which will search the dom and inject the necessary children.

I'll give your proposal here a shot and report back; considering I also already have to create a plugin for this integration to hook into page changes (must invoke another method when that finished) it shouldn't be too hard to test out.

**Comment by kbarnesMCC** [comment]
Just following up confirming this worked just fine. Thanks for the help!!!

**Comment by kbarnesMCC** [comment]
@harlan-zw wanted to reply back here; after further evaluation; I suspect that while your proposal works from keeping the `onLoaded` from being invoked multiple times; it actually breaks another desire of mine which I neglected to mention in the original post (apologies for that!)

In essence, I ONLY want this script to be loaded when my Vue Component is actually present on the page. With the plugin approach; the script will ALWAYS be loaded on every route since it's done as part of an overall plugin instead of within the component's `setup` (which wouldn't execute if the component never got put on the page).

We have use cases where we don't want to inject extraneous scripts into the route (e.g. ad-free users). If I go with the plugin route; I would have to build out a separate tracking mechanism to determine if the load the script or not which will complicate the overall application architecture (e.g. can't just use a `v-if` on my component to handle everything).

Do you have any other options? FWIW the `onLoadedSingleton` idea would presumably work.

Thanks,
Ken

**Comment by kbarnesMCC** [comment]
Apologies; I was getting a little confused in my referencing. I can confirm the script itself is not loaded in the DOM until the component is on.

I was referring to the plugin got which sets up the `onLoaded` callback; it gets executed since it's a plugin. That said, to your point; it's not doing anything other than setting up a callback that wouldn't be invoked so not a big deal.

I think I'm good; though it would still be nice to be able to fully encapsulate our "optional" functionality into a VueJS component if y'all decide you want to support a singleton loaded pattern.

Thanks for supporting me throughout this!!!

**Comment by harlan-zw** [comment]
Yes, I'd like to still support the `onLoadedSingleton` but I'm looking for a valid use case in one of the Registry components before committing to it. otherwise I'll take a look at the HTL BID implementation when I have a chance and see what it looks like.
