### ISSUE TITLE
How can I change fetchpriority from 'low' to 'high' (Google Tag Manager)

### ISSUE THREAD

**Issue by pieterjanmaes** [nuxt/scripts#338]
### 📚 Is your documentation request related to a problem?

I want to change `fetchproirity="low"` to `fetchpriority="hight"`.

I made use of  the Google Tag Manager script from the Script Registry.

<img width="672" alt="Image" src="https://github.com/user-attachments/assets/74e8a344-e908-44f6-b061-0982d8e4990a" />

### 🔍 Where should you find it?

I can't find it in the docs, but if you can change the `fetchpriority`, it should be in on the Google Tag Manager page on de Scripts Registry.

=> [scripts.nuxt.com/scripts/tracking/google-tag-manager](https://scripts.nuxt.com/scripts/tracking/google-tag-manager)

**Comment by joaopedrodcf** [comment]
Hey @pieterjanmaes if you look into the JSDocs and types you can find the fetch priority, example:

```ts
const { proxy } = useScriptGoogleTagManager({
        id: "YOUR_ID",
        scriptInput: {
            fetchpriority: "high"
        },
});
```


Hope this helps.
