### ISSUE TITLE
Live Chat Integrations with Facade Components

### ISSUE THREAD

**Issue by harlan-zw** [nuxt/scripts#44]
- [x] [Crisp](https://crisp.chat/en/) - https://github.com/nuxt/scripts/pull/128
- [x] [Intercom](https://www.intercom.com/) - https://github.com/nuxt/scripts/pull/129
- [ ] [Messenger](https://www.facebook.com/business/goals/add-live-chat-to-website-with-messenger)

Similar to https://github.com/calibreapp/react-live-chat-loader

**Comment by maximepvrt** [comment]
Can you support [Crisp](https://crisp.chat/)
