### ISSUE TITLE
Detect & Warn Top Level Await Brick

### ISSUE THREAD

**Issue by harlan-zw** [nuxt/scripts#46]
The following code will potentially brick Vue component as the await won't be resolved until the script loads and the script can't load until the trigger is fired (which relies on the component being mounted in most cases).

```vue
<script setup>
const { $script } = useScript('..')

await $script.load()
// or await $script
</script>
```

**Comment by danielroe** [comment]
Could we implement this as an eslint rule? (cc: @antfu)

**Comment by antfu** [comment]
I don't have the context, but is that saying that users **should not** await for `$script` coming from `useScript`? Should we provide auto-fix/suggestions as well?
