### ISSUE TITLE
[Question]: Usage with web workers (partytown)

### ISSUE THREAD

**Issue by MuhammadM1998** [nuxt/scripts#56]
Hello, Thanks for great work I'm looking forward to use the module

I remember a `strategy` or a similar option being discussed that let the user specify where to load the script. A possible option would be a worker to offload the 3rd party script entirely from the main thread. I can't find that discussion to link it.

Is there a way to use a worker for the scripts? Also will there be some kind of integration with tools like partytown? Thanks!

**Comment by harlan-zw** [comment]
Hi, thanks for the question. I've made an issue here to track further https://github.com/nuxt/scripts/issues/182
