### ISSUE TITLE
Facade Component Benchmarking

### ISSUE THREAD

**Issue by harlan-zw** [nuxt/scripts#79]
We're advertising benchmarks for facade scripts on the home page, while we preface this data as inaccurate there is some opportunity to make this _slightly_ more accurate.

## URLs

Google Maps
- Default https://scripts-phi.vercel.app/third-parties/google-maps/default
- Nuxt Scripts https://scripts-phi.vercel.app/third-parties/google-maps/nuxt-scripts

YouTube
- Default https://scripts-phi.vercel.app/third-parties/youtube/default
- Nuxt Scripts https://scripts-phi.vercel.app/third-parties/youtube/nuxt-scripts

Vimeo
- Default https://scripts-phi.vercel.app/third-parties/vimeo/default
- Nuxt Scripts https://scripts-phi.vercel.app/third-parties/vimeo/nuxt-scripts

**Comment by Aareksio** [comment]
I find the benchmarks very misleading. Technicalities aside, the Nuxt Script demo URLs offer **different** experience from their Default counterparts. Lazy loading scripts is a trade and should be treated as such.

**Comment by harlan-zw** [comment]
> I find the benchmarks very misleading. Technicalities aside, the Nuxt Script demo URLs offer **different** experience from their Default counterparts. Lazy loading scripts is a trade and should be treated as such.

Do you have any suggestions to make this clearer? The benchmarks are for showcasing the benefits of offering a different experience.

It does state that the benchmarks are for Facade Components.

**Comment by Aareksio** [comment]
Current benchmark is confusing - I did not notice the "facade components" in copy on the left. Nor understood what it really means (loading script vs not loading script aka 0ms). It made me thing Nuxt Scripts does something similar to [partytown](https://partytown.builder.io/). I also instinctively extrapolated the examples to other scripts - eg. analytics, ads - which won't _benefit_ from facade components at all.

I can not imagine a path to making "Mastering Web Vitals" clearer, while focusing on facade components. This is a valid approach, my concern is that placing it prominently as 2nd section and first bullet point on landing page gives incorrect impression of what the module is actually doing.

There are benefits Nuxt Scripts provides: local bundling, optimized loading waterfall, SSR proxy. None of them alters the experience significantly. If for marketing reasons the focus is supposed to be on Web Vitals, optimized waterfall alone should do the trick for many benchmarks (FCP, LCP, INP and FID).

---

Also worth considering is the fact the benchmarks are going to be inherently misleading, no matter how you do them. You are measuring a single script in void. The "46.4x faster" label reminds me of vite vs whatever vercel thing was and hot reload. If this is dictated by marketing - keeping it is fine, business is business.

**Comment by harlan-zw** [comment]
Thank you for the feedback.

I'll make sure this is addressed before we have an official announcement. 

The point of the benchmarks is simply to show that using the Facade components will significantly improve your web vitals.

**Comment by harlan-zw** [comment]
The wording should better reflect what we've discussed above now.

![image](https://github.com/nuxt/scripts/assets/5326365/1ddc2af6-58de-46b5-a2af-67343e3d770b)
